export const sageIntacctFieldMaps = {
  customers: {
    Customer: 'customerId',
    Name: 'name',
    Address_1: 'address1',
    City: 'city',
    State: 'state',
    ZIP_Code: 'zipCode',
    Type: 'type',
  },
  vendors: {
    Vendor: 'vendorId',
    Name: 'name',
    Address_1: 'address1',
    City: 'city',
    State: 'state',
    ZIP: 'zip',
    Type: 'type',
  },
  jobs: {
    Job: 'jobId',
    Well: 'well',
    Description: 'description',
    County: 'county',
    Unique_Job: 'uniqueJob',
    Record_Type_Name: 'recordTypeName',
    Status: 'status',
    AR_Customer: 'customerId',
    WorkTypeId: 'workTypeId',
  },
  invoices: {
    Sage_ID: 'sageId',
    Vendor: 'vendorId',
    Invoice_Date: 'invoiceDate',
    Invoice: 'invoiceNumber',
    Vendor_Invoice_Number: 'vendorInvoiceNumber',
    Description: 'description',
    Amount: 'amount',
  },
  invoiceLines: {
    Sage_ID: 'sageId',
    Invoice_Sage_ID: 'invoiceSageId',
    Parent_Invoice_Sage_ID: 'parentInvoiceSageId',
    Job: 'jobId',
    Unique_Job: 'uniqueJob',
    Cost_Code: 'costCode',
    Activity_Status: 'activityStatus',
    Activity_Date: 'activityDate',
    Transaction_Date: 'transactionDate',
    Amount: 'amount',
    Vendor_Sage_ID: 'vendorSageId',
    Expense_Account: 'expenseAccount',
    Description: 'description',
  },
  equipment: {
    Equipment: 'equipmentId',
    Description: 'description',
    Status: 'status',
  },
  inventory: {
    Row_ID: 'rowId',
    Accounting_Date: 'accountingDate',
    Amount: 'amount',
    Date_Stamp: 'dateStamp',
    Description: 'description',
    JC_Transaction_Type: 'jcTransactionType',
    Transaction_Date: 'transactionDate',
    Unit_Cost: 'unitCost',
    Units: 'units',
    Cost_Code: 'costCode',
    Job: 'jobId',
    Unique_Job_Number: 'uniqueJobNumber',
  },
} as const;

export function getFieldMap(sourceKey: keyof typeof sageIntacctFieldMaps) {
  return sageIntacctFieldMaps[sourceKey];
}
