import type { SageIntacctObjectDefinition } from './types';

export const sageIntacctObjectCatalog: SageIntacctObjectDefinition[] = [
  {
    key: 'customers',
    label: 'Customers',
    sourceObject: 'CUSTOMER / customers.csv',
    targetEntity: 'Customer',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'Customer',
    description: 'Global customer master data used by jobs and revenue reporting.',
    requiredFields: ['Customer', 'Name', 'Address_1', 'City', 'State', 'ZIP_Code', 'Type'],
    recommendedCadence: 'Daily or on demand',
    readiness: 'active-csv',
  },
  {
    key: 'vendors',
    label: 'Vendors',
    sourceObject: 'VENDOR / vendors.csv',
    targetEntity: 'Vendor',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'Vendor',
    description: 'Vendor master records for AP bills, invoice lines, spend analytics and job costing.',
    requiredFields: ['Vendor', 'Name', 'Address_1', 'City', 'State', 'ZIP', 'Type'],
    recommendedCadence: 'Daily or on demand',
    readiness: 'active-csv',
  },
  {
    key: 'jobs',
    label: 'Jobs',
    sourceObject: 'PROJECT / jobs.csv',
    targetEntity: 'Job',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'Job',
    description: 'SDI jobs/projects. Owning company is derived from the middle segment of the job number.',
    requiredFields: ['Job', 'Unique_Job', 'AR_Customer', 'Status', 'Description'],
    recommendedCadence: 'Daily or on demand',
    readiness: 'active-csv',
  },
  {
    key: 'invoices',
    label: 'AP Bills / Invoices',
    sourceObject: 'APBILL / invoices.csv',
    targetEntity: 'Invoice',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'Sage_ID',
    description: 'AP bill headers used to explain vendor spend, approvals and job cost context.',
    requiredFields: ['Sage_ID', 'Vendor', 'Invoice_Date', 'Invoice', 'Vendor_Invoice_Number', 'Amount'],
    recommendedCadence: 'Daily or on demand',
    readiness: 'active-csv',
  },
  {
    key: 'invoiceLines',
    label: 'Invoice Lines',
    sourceObject: 'APBILLITEM / invoice-lines.csv',
    targetEntity: 'InvoiceLine',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'Sage_ID',
    description: 'The most important job-costing dataset: links AP spend to jobs, vendors, cost codes and invoices.',
    requiredFields: ['Sage_ID', 'Parent_Invoice_Sage_ID', 'Job', 'Unique_Job', 'Cost_Code', 'Amount'],
    recommendedCadence: 'Daily or on demand',
    readiness: 'active-csv',
  },
  {
    key: 'equipment',
    label: 'Equipment',
    sourceObject: 'Equipment dimension / equipment.csv',
    targetEntity: 'Equipment',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'Equipment',
    description: 'Equipment/asset register. Owning company is derived from the first segment of the equipment number.',
    requiredFields: ['Equipment', 'Description', 'Status'],
    recommendedCadence: 'Daily or on demand',
    readiness: 'active-csv',
  },
  {
    key: 'inventory',
    label: 'Inventory Transactions',
    sourceObject: 'Inventory / inventory.csv',
    targetEntity: 'InventoryTransaction',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'Row_ID',
    description: 'Inventory usage connected to jobs and included in job profitability while still shown separately.',
    requiredFields: ['Row_ID', 'Job', 'Unique_Job_Number', 'Amount', 'Unit_Cost', 'Units', 'Cost_Code'],
    recommendedCadence: 'Daily or on demand',
    readiness: 'active-csv',
  },
  {
    key: 'glEntries',
    label: 'GL Entries',
    sourceObject: 'GLENTRY',
    targetEntity: 'GeneralLedgerEntry',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'RECORDNO',
    description: 'Future API-backed financial journal details for reconciliations, POR journals and accounting analytics.',
    requiredFields: ['RECORDNO', 'ACCOUNTNO', 'AMOUNT', 'LOCATIONID'],
    recommendedCadence: 'Scheduled API sync',
    readiness: 'api-ready',
  },
  {
    key: 'dimensions',
    label: 'Dimensions',
    sourceObject: 'LOCATION / DEPARTMENT / TASK / PROJECT',
    targetEntity: 'Dimension',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'ID',
    description: 'Dimension metadata for company/entity access, job ownership, cost codes and reporting filters.',
    requiredFields: ['ID', 'NAME', 'STATUS'],
    recommendedCadence: 'Daily API sync',
    readiness: 'api-ready',
  },
  {
    key: 'attachments',
    label: 'Attachments',
    sourceObject: 'SUPDOC / attachments',
    targetEntity: 'DocumentRecord',
    syncDirection: 'intacct-to-sdi',
    primaryKey: 'RECORDNO',
    description: 'Future invoice/document attachment synchronization into SDI One document workspaces.',
    requiredFields: ['RECORDNO', 'FILENAME'],
    recommendedCadence: 'On demand or nightly',
    readiness: 'future',
  },
];

export function getSageObject(key: string) {
  return sageIntacctObjectCatalog.find((object) => object.key === key);
}
