import type { SalesforceObjectDefinition } from './types';

export const salesforceObjectCatalog: SalesforceObjectDefinition[] = [
  {
    key: 'accounts',
    label: 'Accounts',
    sourceObject: 'Account',
    targetEntity: 'Customer',
    syncDirection: 'bidirectional',
    externalId: 'Sage_ID__c / Customer',
    description: 'Customer/account context from Salesforce, matched to SDI One customers through Sage/customer identifiers.',
    requiredFields: ['Id', 'Name', 'Sage_ID__c'],
    recommendedCadence: 'Hourly API sync or Data Loader bridge',
    readiness: 'api-ready',
  },
  {
    key: 'contacts',
    label: 'Contacts',
    sourceObject: 'Contact',
    targetEntity: 'Contact',
    syncDirection: 'salesforce-to-sdi',
    externalId: 'Id',
    description: 'Customer contacts and relationship context for CRM workspaces.',
    requiredFields: ['Id', 'AccountId', 'FirstName', 'LastName', 'Email', 'Phone'],
    recommendedCadence: 'Hourly API sync',
    readiness: 'api-ready',
  },
  {
    key: 'opportunities',
    label: 'Opportunities',
    sourceObject: 'Opportunity',
    targetEntity: 'Opportunity',
    syncDirection: 'salesforce-to-sdi',
    externalId: 'Id',
    description: 'Pipeline, estimates, forecast and won/lost history that feeds executive revenue forecasting.',
    requiredFields: ['Id', 'Name', 'AccountId', 'StageName', 'Amount', 'CloseDate'],
    recommendedCadence: 'Hourly API sync',
    readiness: 'api-ready',
  },
  {
    key: 'jobs',
    label: 'Jobs / Work Orders',
    sourceObject: 'CW_Job_Work_Order__c',
    targetEntity: 'Job',
    syncDirection: 'bidirectional',
    externalId: 'CW_Unique_Job_Number__c',
    description: 'Salesforce job/work order object aligned to SDI One Jobs through Unique_Job.',
    requiredFields: ['Id', 'CW_Unique_Job_Number__c', 'Name'],
    recommendedCadence: 'Hourly API sync / Data Loader bridge',
    readiness: 'data-loader-active',
  },
  {
    key: 'thirdPartyInvoices',
    label: 'Third Party Invoices',
    sourceObject: 'Third_Party_Invoice__c',
    targetEntity: 'Invoice',
    syncDirection: 'sdi-to-salesforce',
    externalId: 'Sage_ID__c',
    description: 'Invoice header records pushed from Sage/SDI One into Salesforce for job and customer visibility.',
    requiredFields: ['Sage_ID__c', 'Name', 'Vendor_Sage_ID__c'],
    recommendedCadence: 'Scheduled upsert after Sage import',
    readiness: 'data-loader-active',
  },
  {
    key: 'thirdPartyInvoiceLines',
    label: 'Third Party Invoice Lines',
    sourceObject: 'Third_Party_Invoice_Line__c',
    targetEntity: 'InvoiceLine',
    syncDirection: 'sdi-to-salesforce',
    externalId: 'Sage_ID__c',
    description: 'AP bill line records upserted to Salesforce, linked to invoice, job/work order, product/cost code and amount.',
    requiredFields: ['Sage_ID__c', 'Parent_Invoice_Sage_ID__c', 'Unique_Job__c', 'Amount__c'],
    recommendedCadence: 'Scheduled upsert after Sage import',
    readiness: 'data-loader-active',
  },
  {
    key: 'costCodes',
    label: 'Cost Codes',
    sourceObject: 'Cost_Code__c / CW_Product__c',
    targetEntity: 'CostCode',
    syncDirection: 'salesforce-to-sdi',
    externalId: 'Cost_Code_Sage_ID__c / CW_UniqueID__c',
    description: 'Cost code/product metadata used to relate invoice lines to job costing categories.',
    requiredFields: ['Id', 'Name', 'Cost_Code_Sage_ID__c'],
    recommendedCadence: 'Daily API sync',
    readiness: 'api-ready',
  },
  {
    key: 'products',
    label: 'Products',
    sourceObject: 'Product2',
    targetEntity: 'Product',
    syncDirection: 'salesforce-to-sdi',
    externalId: 'ProductCode / CW_UniqueID__c',
    description: 'Salesforce product metadata for invoice line lookup and cost code relationships.',
    requiredFields: ['Id', 'Name', 'ProductCode'],
    recommendedCadence: 'Daily API sync',
    readiness: 'api-ready',
  },
  {
    key: 'activities',
    label: 'Activities',
    sourceObject: 'Task / Event',
    targetEntity: 'Activity',
    syncDirection: 'salesforce-to-sdi',
    externalId: 'Id',
    description: 'CRM activities that will feed customer and job timelines.',
    requiredFields: ['Id', 'Subject', 'WhoId', 'WhatId', 'ActivityDate'],
    recommendedCadence: 'Hourly API sync',
    readiness: 'future',
  },
  {
    key: 'files',
    label: 'Files',
    sourceObject: 'ContentDocument / ContentVersion',
    targetEntity: 'DocumentRecord',
    syncDirection: 'salesforce-to-sdi',
    externalId: 'Id',
    description: 'Future Salesforce files/attachments sync into SDI One document workspaces.',
    requiredFields: ['Id', 'Title', 'FileType'],
    recommendedCadence: 'On demand or nightly',
    readiness: 'future',
  },
];

export function getSalesforceObject(key: string) {
  return salesforceObjectCatalog.find((object) => object.key === key);
}
