import { PageHeader } from '../../../../components/ui/PageHeader';
import { SimpleTable } from '../../../../components/ui/SimpleTable';
import { StatusBadge } from '../../../../components/ui/StatusBadge';
import { prisma } from '../../../../lib/prisma';

export default async function TasksPage() {
  const tasks = await prisma.taskItem.findMany({ orderBy: [{ status: 'asc' }, { createdAt: 'desc' }], take: 200 });
  return <>
    <PageHeader title="Task Engine" description="Action items generated by workflows, approvals, business rules, integrations, and users." />
    <SimpleTable rows={tasks} columns={[
      { key: 'title', label: 'Task' },
      { key: 'taskType', label: 'Type' },
      { key: 'priority', label: 'Priority', render: (r:any) => <StatusBadge value={r.priority} /> },
      { key: 'status', label: 'Status', render: (r:any) => <StatusBadge value={r.status} /> },
      { key: 'assignedTo', label: 'Assigned To' },
      { key: 'entityType', label: 'Entity' },
    ]} />
  </>;
}
