export const porFieldMaps = {
  equipment_item_file: {
    Key: 'equipmentId',
    Name: 'description',
    Category: 'category',
    'Serial No': 'serialNumber',
    Manuf: 'manufacturer',
    'Model No.': 'modelNumber',
    'Model Year': 'modelYear',
    Status: 'status',
  },
  repair_costs: {
    Equipment: 'equipmentId',
    'Repair Cost MTD': 'repairCostMtd',
    'Repair Cost LTD': 'repairCostLtd',
    'As Of Date': 'asOfDate',
    Category: 'category',
    Status: 'status',
  },
  rental_history: {
    Equipment: 'equipmentId',
    Job: 'jobId',
    Customer: 'customerId',
    'Start Date': 'startedAt',
    'End Date': 'endedAt',
    Rate: 'rate',
    Revenue: 'revenue',
    Company: 'companyId',
  },
  availability: {
    Equipment: 'equipmentId',
    Status: 'status',
    Location: 'location',
    'Current Job': 'currentJobId',
    'Reserved Until': 'reservedUntil',
  },
  sage_cost_push: {
    Equipment: 'equipmentId',
    'Repair Cost MTD': 'repairCostMtd',
    'Repair Cost LTD': 'repairCostLtd',
    Description: 'description',
    Category: 'category',
    'As Of Date': 'asOfDate',
  },
} as const;
