import type { PorObjectDefinition } from './types';

export const porObjectCatalog: PorObjectDefinition[] = [
  {
    key: 'equipment_item_file',
    sourceObject: 'POR Item File',
    label: 'Equipment / Item File',
    description: 'POR equipment master data including asset number, name, category, serial number, manufacturer, model and year.',
    targetEntity: 'Equipment',
    externalId: 'Equipment',
    syncDirection: 'por-to-sdi',
    requiredFields: ['Key', 'Name', 'Category'],
    optionalFields: ['Serial No', 'Manuf', 'Model No.', 'Model Year', 'Status'],
    readiness: 'ready',
  },
  {
    key: 'repair_costs',
    sourceObject: 'POR Repair Cost MTD/LTD',
    label: 'Repair Costs',
    description: 'MTD/LTD repair cost values used to evaluate equipment profitability and maintenance burden.',
    targetEntity: 'EquipmentCostSnapshot',
    externalId: 'Equipment',
    syncDirection: 'por-to-sdi',
    requiredFields: ['Equipment', 'Repair Cost MTD', 'Repair Cost LTD'],
    optionalFields: ['As Of Date', 'Category', 'Status'],
    readiness: 'bridge',
  },
  {
    key: 'rental_history',
    sourceObject: 'POR Rental History',
    label: 'Rental History',
    description: 'Rental usage history for internal and external equipment utilization, revenue and job assignment.',
    targetEntity: 'EquipmentRentalEvent',
    externalId: 'Rental Ticket / Contract',
    syncDirection: 'por-to-sdi',
    requiredFields: ['Equipment', 'Start Date', 'End Date'],
    optionalFields: ['Job', 'Customer', 'Rate', 'Revenue', 'Company'],
    readiness: 'future',
  },
  {
    key: 'availability',
    sourceObject: 'POR Availability',
    label: 'Availability',
    description: 'Current availability / rented / repair status to power asset operations and dispatch decisions.',
    targetEntity: 'EquipmentAvailability',
    externalId: 'Equipment',
    syncDirection: 'por-to-sdi',
    requiredFields: ['Equipment', 'Status'],
    optionalFields: ['Location', 'Current Job', 'Reserved Until'],
    readiness: 'future',
  },
  {
    key: 'sage_cost_push',
    sourceObject: 'Sage Equipment Costs',
    label: 'Sage → POR Cost Push',
    description: 'Prepared outbound payloads from Sage/SDI One to update POR repair cost MTD/LTD targets.',
    targetEntity: 'PointOfRentalOutboundCostUpdate',
    externalId: 'Equipment',
    syncDirection: 'sdi-to-por',
    requiredFields: ['Equipment', 'Repair Cost MTD', 'Repair Cost LTD'],
    optionalFields: ['Description', 'Category', 'As Of Date'],
    readiness: 'bridge',
  },
];
